/**
 * Module 1 Example 1.1: SystemVerilog Class Basics
 * Demonstrates classes, inheritance, and special methods for verification.
 * 
 * LEARNING OBJECTIVES:
 *   1. Understand SystemVerilog class syntax and semantics
 *   2. Learn object-oriented programming concepts in verification
 *   3. Master inheritance and polymorphism for transaction modeling
 *   4. Implement standard verification methods (copy, compare, convert2string)
 *   5. Understand static vs instance variables
 * 
 * VERIFICATION PATTERNS DEMONSTRATED:
 *   - Transaction class design (foundation for UVM)
 *   - Factory pattern preparation (class-based object creation)
 *   - Polymorphism (base class handles, derived class objects)
 *   - Standard verification methods (copy, compare, print)
 * 
 * UVM RELATIONSHIP:
 *   - This Transaction class is similar to uvm_sequence_item
 *   - copy() method is similar to uvm_object::copy()
 *   - compare() method is similar to uvm_object::compare()
 *   - convert2string() is similar to uvm_object::convert2string()
 * 
 * Note: This is a standalone example without UVM dependency.
 * For UVM-compatible transactions, see the UVM testbenches.
 * 
 * BEST PRACTICES:
 *   - Always implement copy(), compare(), and convert2string() methods
 *   - Use static variables for class-wide counters
 *   - Provide default values for constructor parameters
 *   - Check for null pointers in methods that accept object references
 */

// ============================================================================
// PACKAGE DECLARATION
// ============================================================================
// Package declaration: creates a namespace for related classes and types
// Packages allow code organization and prevent naming conflicts
// 
// PACKAGE BENEFITS:
//   - Namespace isolation: Prevents name collisions
//   - Code reuse: Can be imported into multiple modules
//   - Organization: Groups related functionality together
//   - Compilation: Packages are compiled once, used many times
// 
// IMPORT SYNTAX:
//   - 'import transaction_pkg::*;' - Import all items (wildcard)
//   - 'import transaction_pkg::Transaction;' - Import specific item
//   - 'transaction_pkg::Transaction' - Use fully qualified name (no import needed)
// 
// 'transaction_pkg' is the package name, can be imported with 'import transaction_pkg::*;'
package transaction_pkg;
    // ============================================================================
    // BASE TRANSACTION CLASS
    // ============================================================================
    /**
     * Base transaction class for verification.
     * 
     * This class demonstrates:
     * - Class definition and object-oriented concepts
     * - Instance variables (object-specific data)
     * - Static variables (class-wide data)
     * - Methods (functions and tasks)
     * - Special methods (copy, compare, convert2string)
     * 
     * TRANSACTION CLASS PURPOSE:
     *   A transaction class is the fundamental building block for verification.
     *   It encapsulates data and operations related to a single bus transaction.
     *   Transactions flow through the verification environment:
     *     1. Generated by sequences/sequences
     *     2. Processed by drivers
     *     3. Monitored by monitors
     *     4. Compared in scoreboards
     * 
     * CLASS vs MODULE:
     *   - Class: Dynamic, can create multiple instances, supports inheritance
     *   - Module: Static, instantiated at compile time, no inheritance
     *   - Classes are used for testbench (verification), modules for DUT (design)
     */
    class Transaction;
        // ========================================================================
        // STATIC (CLASS) VARIABLES
        // ========================================================================
        // Class variable (static): shared across all instances of the class
        // 
        // STATIC VARIABLE SEMANTICS:
        //   - 'static' means this variable belongs to the class, not individual objects
        //   - All Transaction objects share the same id_counter
        //   - Access: Transaction::id_counter (class scope) or Transaction.id_counter (instance)
        //   - Lifetime: Exists for entire simulation (not tied to object lifetime)
        //   - Initialization: Initialized once when class is first referenced
        // 
        // USE CASE: Unique ID generation
        //   - Each transaction needs a unique identifier
        //   - Static counter ensures uniqueness across all instances
        //   - Thread-safe in SystemVerilog (no race conditions in single-threaded simulation)
        // 
        // Initialized to 0, increments each time a new Transaction is created
        static int id_counter = 0;
        
        // ========================================================================
        // INSTANCE VARIABLES (OBJECT DATA MEMBERS)
        // ========================================================================
        // Instance variables: each object has its own copy of these variables
        // These are the "data members" of the class
        // 
        // DATA TYPES:
        //   - 'int': 32-bit signed integer (-2^31 to 2^31-1)
        //   - 'bit [31:0]': 32-bit unsigned bit vector (0 to 2^32-1)
        //   - 'int unsigned': 32-bit unsigned integer (0 to 2^32-1)
        // 
        // 'int' is a 32-bit signed integer type
        int id;              // Unique identifier for this transaction instance
                              // Assigned from static id_counter in constructor
                              // Used for tracking and debugging transactions
        
        // 'bit [31:0]' declares a 32-bit unsigned bit vector (bits 31 down to 0)
        // Bit vector syntax: [MSB:LSB] where MSB=Most Significant Bit, LSB=Least Significant
        bit [31:0] data;      // 32-bit data field for transaction payload
                              // Stores the actual data being transferred
                              // Range: 0x00000000 to 0xFFFFFFFF
        
        // 'int unsigned' is a 32-bit unsigned integer
        int unsigned timestamp;  // Timestamp when transaction was created/processed
                                 // Used for timing analysis and debugging
                                 // Typically set using $time or simulation time
                                 // Unsigned because time is always positive
        
        // ========================================================================
        // CONSTRUCTOR
        // ========================================================================
        /**
         * Constructor: called automatically when object is created with 'new()'
         * 
         * CONSTRUCTOR PURPOSE:
         *   - Initialize object to a known good state
         *   - Allocate resources if needed
         *   - Set default values for instance variables
         * 
         * CONSTRUCTOR CALL:
         *   Transaction txn;           // Declare handle (null pointer)
         *   txn = new();               // Create object, calls constructor
         *   txn = new("MyTxn");        // Create with name parameter
         * 
         * @param name Optional string parameter for object name (not used in this example)
         *              Default value "Transaction" allows calling new() without arguments
         *              In UVM, this would be used for hierarchical naming
         */
        function new(string name = "Transaction");
            // Increment the shared class counter
            // This ensures each transaction gets a unique ID
            // 
            // ID GENERATION ALGORITHM:
            //   1. First transaction: id_counter=0 -> increment to 1 -> id=1
            //   2. Second transaction: id_counter=1 -> increment to 2 -> id=2
            //   3. And so on...
            // 
            // IMPORTANT: Pre-increment (++id_counter) vs post-increment (id_counter++)
            //   - Current: Post-increment (increment after use)
            //   - Result: First transaction gets id=1 (not 0)
            //   - Alternative: Pre-increment would give id=0 for first transaction
            id_counter++;
            
            // Assign the incremented counter value to this instance's ID
            // This gives each transaction a unique identifier
            // Useful for: Debugging, tracking, scoreboard matching
            id = id_counter;
            
            // Initialize data field to zero
            // Default value: 0x00000000
            // User should set this to actual transaction data after creation
            data = 0;
            
            // Initialize timestamp to zero (can be set later with set_timestamp)
            // Default value: 0 (indicates not yet timestamped)
            // Typically set when transaction is processed: set_timestamp($time)
            timestamp = 0;
        endfunction
        
        // ========================================================================
        // COPY METHOD (DEEP COPY)
        // ========================================================================
        /**
         * Copy method: creates a deep copy of another transaction
         * 
         * COPY SEMANTICS:
         *   - Deep copy: Copies all data members (not just the handle)
         *   - Shallow copy: Would only copy the handle (not implemented here)
         *   - This method modifies 'this' object (the object calling copy)
         * 
         * USE CASES:
         *   - Cloning transactions before sending to multiple destinations
         *   - Saving transaction state for later comparison
         *   - Creating backup copies before modification
         *   - Implementing transaction queues (need copies, not references)
         * 
         * UVM EQUIVALENT: uvm_object::copy(uvm_object rhs)
         * 
         * This is a common pattern in verification for duplicating transactions.
         * Used when you need to preserve a transaction's state.
         * 
         * @param rhs Right-hand side: the transaction to copy from
         *            'rhs' is a common naming convention (right-hand side)
         *            Represents the source object being copied
         */
        function void copy(Transaction rhs);
            // Null pointer check: prevent errors if rhs is null
            // 
            // NULL POINTER SAFETY:
            //   - Always check for null before accessing object members
            //   - Prevents simulation crashes from null pointer dereference
            //   - Provides meaningful error messages for debugging
            // 
            // 'rhs == null' checks if the pointer is null (no object assigned)
            // In SystemVerilog, handles can be null if:
            //   - Declared but never assigned: Transaction txn; (txn is null)
            //   - Explicitly set to null: txn = null;
            if (rhs == null) begin
                // Print error message and return early
                // '$error' is a SystemVerilog reporting macro (severity: ERROR)
                // Other reporting macros: $info, $warning, $fatal
                $error("Copy failed: null pointer");
                // Exit function early to prevent null pointer dereference
                // 'return' exits the function immediately
                return;
            end
            
            // Copy all instance variables from source to destination
            // This is a member-by-member copy (deep copy)
            // 
            // COPY OPERATION:
            //   - 'rhs.id' accesses the id field of the right-hand side object
            //   - 'id' (without prefix) refers to 'this.id' (the current object)
            //   - Assignment copies the value (not the reference)
            // 
            // NOTE: For complex objects (arrays, nested objects), you may need
            //       to implement deeper copying logic
            id = rhs.id;                    // Copy unique identifier
            data = rhs.data;                // Copy 32-bit data field
            timestamp = rhs.timestamp;       // Copy timestamp value
            
            // NOTE: Static variables (id_counter) are NOT copied
            //       They belong to the class, not individual objects
        endfunction
        
        // ========================================================================
        // COMPARE METHOD (EQUALITY CHECK)
        // ========================================================================
        /**
         * Compare method: checks if two transactions are equivalent
         * 
         * COMPARISON SEMANTICS:
         *   - Equality: Two transactions are equal if their key fields match
         *   - Key fields: id and data (timestamp is ignored)
         *   - Returns: 1 (true) if match, 0 (false) if mismatch
         * 
         * USE CASES:
         *   - Scoreboard: Compare expected vs actual transactions
         *   - Transaction matching: Find matching transactions in queues
         *   - Debugging: Verify transaction integrity
         *   - Test assertions: Check transaction correctness
         * 
         * UVM EQUIVALENT: uvm_object::compare(uvm_object rhs, uvm_comparer comparer)
         * 
         * This is used for checking expected vs actual transactions in scoreboards.
         * Returns 1 (true) if transactions match, 0 (false) otherwise.
         * 
         * @param rhs Right-hand side: the transaction to compare with
         *            'this' is the left-hand side (lhs), 'rhs' is right-hand side
         * @return 1 if transactions match (same id and data), 0 otherwise
         */
        function bit compare(Transaction rhs);
            // Null pointer check: if rhs is null, transactions cannot match
            // 
            // NULL HANDLING:
            //   - Comparing with null always returns false
            //   - This prevents null pointer dereference errors
            //   - Early return for efficiency
            if (rhs == null) return 0;  // Return false (0) if comparing with null
            
            // Compare both id and data fields
            // 
            // COMPARISON LOGIC:
            //   - 'id == rhs.id': Compare unique identifiers
            //   - 'data == rhs.data': Compare data payloads
            //   - '&&': Logical AND - both must be true for match
            //   - '==' is equality operator: returns 1 if equal, 0 if not
            // 
            // EQUALITY DEFINITION:
            //   - Two transactions are equal if they have the same id AND data
            //   - This is a strict equality (both fields must match)
            //   - Alternative: Could compare only data (ignore id)
            //   - Alternative: Could use fuzzy matching (tolerance for data)
            return (id == rhs.id) && (data == rhs.data);
            
            // Note: timestamp is not compared, only id and data matter for equality
            // 
            // DESIGN DECISION: Why ignore timestamp?
            //   - Timestamps represent when transaction was processed
            //   - Two identical transactions processed at different times should match
            //   - Timestamp is metadata, not part of transaction identity
            //   - If timestamp comparison needed, add separate method: compare_with_time()
        endfunction
        
        // ========================================================================
        // CONVERT2STRING METHOD (STRING REPRESENTATION)
        // ========================================================================
        /**
         * String conversion - equivalent to __str__ in Python or toString() in Java
         * 
         * STRING FORMATTING:
         *   - Provides human-readable representation of transaction
         *   - Essential for debugging and logging
         *   - Should include all key fields for identification
         * 
         * USE CASES:
         *   - Debug output: $display("Transaction: %s", txn.convert2string());
         *   - Log files: Write transaction details to log
         *   - Error messages: Include transaction info in error reports
         *   - Waveform annotation: Display transaction info in waveforms
         * 
         * UVM EQUIVALENT: uvm_object::convert2string()
         * 
         * This method provides a human-readable string representation of the transaction.
         * Used for debugging and logging purposes.
         * 
         * @return Formatted string containing transaction fields
         *         Format: "Transaction(id=<id>, data=0x<hex>, timestamp=<time>)"
         */
        function string convert2string();
            // '$sformatf' is SystemVerilog's sprintf function: formats string with placeholders
            // Similar to printf() in C or format() in Python
            // 
            // FORMAT SPECIFIERS:
            //   - '%0d': Decimal integer, no leading zeros (0 means minimal width)
            //   - '%0h': Hexadecimal integer, no leading zeros, lowercase
            //   - '%0H': Hexadecimal integer, uppercase
            //   - '%0x': Same as %0h (hexadecimal)
            //   - '%s': String
            //   - '%f': Floating point
            // 
            // FORMAT STRING BREAKDOWN:
            //   - "Transaction(id=%0d, data=0x%0h, timestamp=%0d)"
            //   - %0d (first): Formats id as decimal
            //   - %0h: Formats data as hexadecimal (with 0x prefix in literal)
            //   - %0d (second): Formats timestamp as decimal
            // 
            // ARGUMENTS:
            //   - id: Transaction ID (integer)
            //   - data: Transaction data (32-bit, displayed as hex)
            //   - timestamp: Transaction timestamp (integer)
            // 
            // Returns a formatted string with all transaction fields
            return $sformatf("Transaction(id=%0d, data=0x%0h, timestamp=%0d)", 
                           id, data, timestamp);
            
            // EXAMPLE OUTPUT:
            //   "Transaction(id=1, data=0x1234, timestamp=100)"
        endfunction
        
        // ========================================================================
        // SET_TIMESTAMP METHOD (MUTATOR)
        // ========================================================================
        /**
         * Set transaction timestamp
         * 
         * MUTATOR METHOD:
         *   - Allows modification of object state after creation
         *   - Provides controlled access to instance variables
         *   - Can add validation logic if needed
         * 
         * TIMESTAMP USAGE:
         *   - Track when transaction was created: set_timestamp($time)
         *   - Track when transaction was processed: set_timestamp($time)
         *   - Timing analysis: Calculate transaction latency
         *   - Debugging: Identify transaction timing issues
         * 
         * Allows setting the timestamp after object creation.
         * Useful for tracking when transactions are processed.
         * 
         * @param ts Unsigned integer timestamp value to assign
         *           Typically obtained from $time or $realtime
         *           Should be non-negative (unsigned ensures this)
         */
        function void set_timestamp(int unsigned ts);
            // Assign the provided timestamp value to the instance variable
            // 
            // ASSIGNMENT:
            //   - Direct assignment: timestamp = ts;
            //   - No validation: Could add range checking if needed
            //   - No side effects: Simple setter method
            timestamp = ts;
            
            // ALTERNATIVE IMPLEMENTATION (with validation):
            //   if (ts > MAX_TIMESTAMP) begin
            //       $warning("Timestamp exceeds maximum: %0d", ts);
            //   end
            //   timestamp = ts;
        endfunction
        
        // ========================================================================
        // GET_ID METHOD (ACCESSOR)
        // ========================================================================
        /**
         * Get transaction ID
         * 
         * ACCESSOR METHOD (GETTER):
         *   - Provides read-only access to instance variable
         *   - Encapsulation: Hides internal implementation
         *   - Can add logic (validation, formatting) if needed later
         * 
         * ENCAPSULATION BENEFITS:
         *   - If id storage changes, only this method needs updating
         *   - Can add logging: Log every ID access
         *   - Can add validation: Verify ID is valid before returning
         * 
         * Accessor method to retrieve the transaction's unique identifier.
         * Provides controlled access to the id field.
         * 
         * @return The transaction's unique ID (integer)
         *         Range: 1 to maximum (depends on id_counter)
         *         Never returns 0 (first transaction gets id=1)
         */
        function int get_id();
            // Return the instance's id field
            // 
            // RETURN SEMANTICS:
            //   - Returns by value (not by reference)
            //   - Caller gets a copy of the ID
            //   - Modifying return value doesn't affect object
            return id;
            
            // USAGE EXAMPLE:
            //   Transaction txn = new();
            //   int my_id = txn.get_id();  // Get ID value
            //   $display("ID: %0d", my_id);
        endfunction
    endclass  // End of Transaction class definition
    
    /**
     * Read transaction class.
     * 
     * Demonstrates inheritance and method overriding.
     * This class extends (inherits from) the base Transaction class.
     * It adds address-specific fields and methods for read operations.
     */
    class ReadTransaction extends Transaction;
        // Additional instance variables specific to read transactions
        // 'bit [15:0]' declares a 16-bit unsigned bit vector (bits 15 down to 0)
        bit [15:0] address;        // Memory address to read from (16-bit)
        // 'string' is a SystemVerilog string type (dynamic length)
        string transaction_type;  // Type identifier: "READ"
        
        /**
         * Constructor for ReadTransaction
         * 
         * Must call parent class constructor using 'super.new()'
         * 
         * @param name Optional string parameter (defaults to "ReadTransaction")
         */
        function new(string name = "ReadTransaction");
            // Call parent class (Transaction) constructor
            // 'super' refers to the parent class
            // This initializes inherited fields (id, data, timestamp)
            super.new(name);
            // Initialize read-specific fields
            address = 0;                    // Default address is 0
            transaction_type = "READ";     // Set transaction type identifier
        endfunction
        
        /**
         * Override string representation
         * 
         * This method overrides the parent class's convert2string() method.
         * Provides a more specific string representation for read transactions.
         * 
         * @return Formatted string with read transaction fields including address
         */
        function string convert2string();
            // Format string specific to read transactions
            // Includes address field which is unique to read/write transactions
            return $sformatf("ReadTransaction(id=%0d, address=0x%0h, data=0x%0h)", 
                           id, address, data);
        endfunction
        
        /**
         * Get read address
         * 
         * Accessor method to retrieve the memory address for this read transaction.
         * 
         * @return 16-bit address value
         */
        function bit [15:0] get_address();
            // Return the instance's address field
            return address;
        endfunction
    endclass  // End of ReadTransaction class definition
    
    /**
     * Write transaction class.
     * 
     * Demonstrates inheritance and method overriding.
     * This class extends (inherits from) the base Transaction class.
     * It adds address-specific fields and methods for write operations.
     */
    class WriteTransaction extends Transaction;
        // Additional instance variables specific to write transactions
        // 'bit [15:0]' declares a 16-bit unsigned bit vector (bits 15 down to 0)
        bit [15:0] address;        // Memory address to write to (16-bit)
        // 'string' is a SystemVerilog string type (dynamic length)
        string transaction_type;  // Type identifier: "WRITE"
        
        /**
         * Constructor for WriteTransaction
         * 
         * Must call parent class constructor using 'super.new()'
         * 
         * @param name Optional string parameter (defaults to "WriteTransaction")
         */
        function new(string name = "WriteTransaction");
            // Call parent class (Transaction) constructor
            // 'super' refers to the parent class
            // This initializes inherited fields (id, data, timestamp)
            super.new(name);
            // Initialize write-specific fields
            address = 0;                    // Default address is 0
            transaction_type = "WRITE";     // Set transaction type identifier
        endfunction
        
        /**
         * Override string representation
         * 
         * This method overrides the parent class's convert2string() method.
         * Provides a more specific string representation for write transactions.
         * 
         * @return Formatted string with write transaction fields including address
         */
        function string convert2string();
            // Format string specific to write transactions
            // Includes address field which is unique to read/write transactions
            return $sformatf("WriteTransaction(id=%0d, address=0x%0h, data=0x%0h)", 
                           id, address, data);
        endfunction
        
        /**
         * Get write address
         * 
         * Accessor method to retrieve the memory address for this write transaction.
         * 
         * @return 16-bit address value
         */
        function bit [15:0] get_address();
            // Return the instance's address field
            return address;
        endfunction
    endclass  // End of WriteTransaction class definition

// End of package definition
endpackage

/**
 * Test program to demonstrate transaction classes
 * 
 * This module demonstrates:
 * - Creating transaction objects
 * - Using inheritance (ReadTransaction, WriteTransaction extend Transaction)
 * - Calling class methods (copy, compare, convert2string)
 * - Polymorphism (derived classes can be used as base class)
 */
module transaction_example;
    // Import all items from the transaction_pkg package
    // 'import transaction_pkg::*;' makes all classes and types available
    // Without this, you would need to use 'transaction_pkg::Transaction'
    import transaction_pkg::*;
    
    // 'initial' block: executes once at simulation start (time 0)
    // This is the test program that demonstrates transaction class usage
    initial begin
        // Variable declarations: declare handles (pointers) to transaction objects
        // These are not objects yet, just handles that can point to objects
        // 'Transaction' is the base class type
        Transaction txn1, txn2;        // Two base transaction handles
        // 'ReadTransaction' is a derived class (inherits from Transaction)
        ReadTransaction read_txn;      // Read transaction handle
        // 'WriteTransaction' is a derived class (inherits from Transaction)
        WriteTransaction write_txn;   // Write transaction handle
        Transaction txn_copy;         // Handle for copied transaction
        
        // Display section header for test output
        // '$display' prints formatted text to console (like printf in C)
        // '====' creates a visual separator in the output
        $display("============================================================");
        $display("Module 1 Example 1.1: SystemVerilog Class Basics");
        $display("============================================================");
        // Empty line for readability
        $display();
        
        // Test 1: Create and use a base transaction object
        $display("1. Creating base transaction:");
        // 'new()' creates a new Transaction object and returns a handle
        // The handle is assigned to txn1, which now points to the object
        txn1 = new();
        // Access instance variable: set the data field to hexadecimal 0x1234
        // '32'h1234' is a 32-bit hexadecimal literal
        txn1.data = 32'h1234;
        // Call convert2string() method to get string representation
        // '%s' is string format specifier
        $display("   %s", txn1.convert2string());
        // Call get_id() method to retrieve the transaction ID
        // '%0d' formats integer in decimal without leading zeros
        $display("   Transaction ID: %0d", txn1.get_id());
        $display();  // Empty line
        
        // Test 2: Create and use a read transaction (demonstrates inheritance)
        $display("2. Creating read transaction (inheritance):");
        // Create a ReadTransaction object (inherits from Transaction)
        // This object has all Transaction fields (id, data, timestamp) plus address
        read_txn = new();
        // Set the address field (specific to ReadTransaction, not in base class)
        // '16'h1000' is a 16-bit hexadecimal literal (4096 in decimal)
        read_txn.address = 16'h1000;
        // Set the data field (inherited from Transaction base class)
        // '32'hDEAD' is a 32-bit hexadecimal literal
        read_txn.data = 32'hDEAD;
        // Call overridden convert2string() method
        // This calls ReadTransaction's version, not Transaction's version
        $display("   %s", read_txn.convert2string());
        // Call get_address() method (specific to ReadTransaction)
        // '%0h' formats integer in hexadecimal without leading zeros
        $display("   Address: 0x%0h", read_txn.get_address());
        $display();  // Empty line
        
        // Test 3: Create and use a write transaction (demonstrates inheritance)
        $display("3. Creating write transaction (inheritance):");
        // Create a WriteTransaction object (inherits from Transaction)
        // This object has all Transaction fields plus address
        write_txn = new();
        // Set the address field (specific to WriteTransaction)
        // '16'h2000' is a 16-bit hexadecimal literal (8192 in decimal)
        write_txn.address = 16'h2000;
        // Set the data field (inherited from Transaction base class)
        // '32'hBEEF' is a 32-bit hexadecimal literal
        write_txn.data = 32'hBEEF;
        // Call overridden convert2string() method
        // This calls WriteTransaction's version, not Transaction's version
        $display("   %s", write_txn.convert2string());
        // Call get_address() method (specific to WriteTransaction)
        $display("   Address: 0x%0h", write_txn.get_address());
        $display();  // Empty line
        
        // Test 4: Demonstrate copy method
        $display("4. Testing copy:");
        // Create a new Transaction object to hold the copy
        txn_copy = new();
        // Call copy() method: copies all fields from txn1 to txn_copy
        // This creates a duplicate transaction with same id, data, and timestamp
        txn_copy.copy(txn1);
        // Display both original and copy to verify they match
        $display("   Original: %s", txn1.convert2string());
        $display("   Copy:     %s", txn_copy.convert2string());
        $display();  // Empty line
        
        // Test 5: Demonstrate compare method
        $display("5. Testing compare:");
        // Create a second transaction for comparison
        txn2 = new();
        // Set data to same value as txn1
        txn2.data = 32'h1234;
        // Manually set ID to match txn1's ID
        // This makes txn2 identical to txn1 (same id and data)
        txn2.id = txn1.id;  // Same ID
        // Call compare() method: returns 1 if transactions match, 0 otherwise
        // txn1 and txn2 should match (same id and data)
        $display("   txn1 == txn2: %0d", txn1.compare(txn2));
        // Compare txn1 (base class) with read_txn (derived class)
        // This should return 0 (false) because they have different IDs
        $display("   txn1 == read_txn: %0d", txn1.compare(read_txn));
        $display();  // Empty line
        
        // Display completion message
        $display("============================================================");
        $display("Example completed successfully!");
        $display("============================================================");
        
        // Wait for 10 time units before finishing
        // '#' is delay operator: pauses execution for specified time
        // This gives time for any final operations to complete
        #10;
        // Terminate simulation: '$finish' stops the simulation
        // This is detected by the C++ testbench which exits the simulation loop
        $finish;
    end  // End of initial block
endmodule  // End of module definition
