/**
 * Module 1 Example 1.4: Data Structures Example - C++ Testbench
 * 
 * This C++ file serves as the testbench wrapper for the SystemVerilog
 * data structures example. It instantiates the Verilator-generated model,
 * manages simulation time, and generates VCD waveform files.
 * 
 * LEARNING OBJECTIVES:
 *   1. Understand Verilator C++ testbench structure
 *   2. Learn how to instantiate Verilator-compiled modules
 *   3. Master simulation time management
 *   4. Generate VCD waveforms for debugging
 *   5. Understand simulation lifecycle management
 * 
 * VERILATOR WORKFLOW:
 *   1. Compile: verilator --cc --exe --build data_structures_example.sv data_structures_example.cpp
 *   2. Run: ./obj_dir/Vdata_structures_example
 *   3. View: gtkwave data_structures_example.vcd
 * 
 * TESTBENCH PATTERNS:
 *   - Module instantiation: Create Verilator-generated class instance
 *   - Time management: Track simulation time with main_time
 *   - Waveform generation: VCD file creation and dumping
 *   - Simulation loop: Evaluate design at each time step
 *   - Resource cleanup: Proper memory management
 * 
 * Purpose:
 *   - Instantiate the Verilator-compiled SystemVerilog module
 *   - Drive the simulation clock and control signals
 *   - Generate VCD waveform files for debugging
 *   - Manage simulation lifecycle (initialization, execution, cleanup)
 */

// ============================================================================
// HEADER INCLUDES
// ============================================================================
// Include the Verilator-generated header for the top-level module
// 
// VERILATOR GENERATION:
//   - Verilator compiles SystemVerilog to C++ classes
//   - Class name: V<module_name> (V prefix + module name)
//   - This header is auto-generated during Verilator compilation
//   - Contains: Class definition, signal accessors, evaluation methods
// 
// This header contains the class definition for the compiled SystemVerilog module
// The class name is 'Vdata_structures_example' (V prefix + module name)
// 
// CLASS STRUCTURE (generated by Verilator):
//   class Vdata_structures_example {
//   public:
//       void eval();              // Evaluate design logic
//       void final();             // Finalize simulation
//       void trace(VerilatedVcdC* tfp, int levels);  // Enable tracing
//       // ... signal accessors ...
//   };
#include "Vdata_structures_example.h"

// Include Verilator core header: provides core simulation functionality
// 
// VERILATED CLASS:
//   - Static methods for global simulation control
//   - Command-line argument processing
//   - Finish detection ($finish handling)
//   - Debugging and assertion control
// 
// Contains Verilated class with static methods for simulation control
// Key methods: commandArgs(), traceEverOn(), gotFinish()
#include "verilated.h"

// Include Verilator VCD tracing header: enables waveform generation
// 
// VCD (Value Change Dump) FORMAT:
//   - Standard format for waveform viewers (GTKWave, ModelSim, etc.)
//   - Records signal value changes with timestamps
//   - Text-based format (human-readable)
//   - Can be compressed for large simulations
// 
// VCD files can be viewed in waveform viewers like GTKWave
// 
// VERILATEDVCDC CLASS:
//   - Manages VCD file creation and writing
//   - Methods: open(), dump(), close()
//   - Automatically handles signal value formatting
#include "verilated_vcd_c.h"

// ============================================================================
// GLOBAL SIMULATION TIME
// ============================================================================
/**
 * Global simulation time variable
 * 
 * SIMULATION TIME SEMANTICS:
 *   - Tracks current simulation time in time units (from timescale directive)
 *   - Incremented by testbench in simulation loop
 *   - Used by SystemVerilog $time system task
 *   - Required for VCD waveform timestamping
 * 
 * TIME RESOLUTION:
 *   - Based on timescale in SystemVerilog: `timescale 1ns/1ps
 *   - main_time=1 means 1ns has elapsed
 *   - Can represent up to 2^64-1 time units (very large simulations)
 * 
 * This variable tracks the current simulation time in time units.
 * It's used by the SystemVerilog $time system task and for VCD dumping.
 * 'vluint64_t' is a Verilator-defined 64-bit unsigned integer type.
 * 
 * TYPE DEFINITION:
 *   - vluint64_t: Verilator's 64-bit unsigned integer
 *   - Equivalent to: uint64_t or unsigned long long
 *   - Range: 0 to 18,446,744,073,709,551,615
 *   - Sufficient for: Billions of years of simulation time at 1ns resolution
 */
vluint64_t main_time = 0;

// ============================================================================
// SYSTEMC TIME STAMP CALLBACK
// ============================================================================
/**
 * SystemC time stamp callback function
 * 
 * CALLBACK PURPOSE:
 *   - Verilator calls this function to get current simulation time
 *   - Required for SystemC integration (if using SystemC)
 *   - Used internally by Verilator for time-dependent operations
 *   - Must be defined for Verilator simulations
 * 
 * FUNCTION SIGNATURE:
 *   - Must return double (for SystemC compatibility)
 *   - Verilator expects this exact function name
 *   - Called automatically by Verilator runtime
 * 
 * This function is called by Verilator to get the current simulation time.
 * It's required for proper time tracking in the simulation.
 * 
 * @return Current simulation time as a double (for SystemC compatibility)
 *         Returns main_time cast to double
 *         Allows fractional time units if needed (though not used here)
 */
double sc_time_stamp() {
    // Return the current simulation time
    // 
    // TYPE CONVERSION:
    //   - main_time is vluint64_t (unsigned integer)
    //   - Return type is double (floating point)
    //   - Implicit conversion: integer to double (no precision loss for integers)
    // 
    // Casting to double allows fractional time units if needed
    // In this example, we use integer time steps, so conversion is straightforward
    return main_time;
}

// ============================================================================
// MAIN FUNCTION - SIMULATION ENTRY POINT
// ============================================================================
/**
 * Main function: Entry point of the C++ testbench
 * 
 * SIMULATION LIFECYCLE:
 *   1. Initialize Verilator simulation environment
 *   2. Create and configure the top-level module instance
 *   3. Set up VCD waveform tracing
 *   4. Run the simulation loop (evaluate design at each time step)
 *   5. Clean up resources (memory deallocation)
 * 
 * MEMORY MANAGEMENT:
 *   - Uses 'new' for heap allocation (module and trace objects)
 *   - Must use 'delete' to prevent memory leaks
 *   - RAII pattern could be used for automatic cleanup (not shown here)
 * 
 * ERROR HANDLING:
 *   - No explicit error handling in this simple example
 *   - Production code should check: file open success, memory allocation, etc.
 * 
 * This function orchestrates the entire simulation:
 * 1. Initialize Verilator simulation environment
 * 2. Create and configure the top-level module instance
 * 3. Set up VCD waveform tracing
 * 4. Run the simulation loop
 * 5. Clean up resources
 * 
 * @param argc Number of command-line arguments
 * @param argv Array of command-line argument strings
 * @return Exit status (0 = success, non-zero = error)
 */
int main(int argc, char** argv) {
    // ========================================================================
    // PHASE 1: INITIALIZATION
    // ========================================================================
    // Initialize Verilator with command-line arguments
    // 
    // COMMAND-LINE PROCESSING:
    //   - Parses Verilator-specific flags (e.g., --trace, --trace-depth)
    //   - Sets internal Verilator configuration
    //   - Allows runtime configuration without recompilation
    // 
    // COMMON FLAGS:
    //   --trace: Enable tracing (though we enable it explicitly)
    //   --trace-depth N: Set trace depth (we use 99)
    //   --debug: Enable debug output
    // 
    // This processes any Verilator-specific flags (e.g., --trace, --trace-depth)
    // Arguments are passed from the command line when running the executable
    Verilated::commandArgs(argc, argv);
    
    // Enable tracing globally for all Verilator modules
    // 
    // TRACING ENABLEMENT:
    //   - Must be called BEFORE creating module instances
    //   - Enables VCD tracing capability system-wide
    //   - Required even if using explicit trace() calls
    // 
    // This must be called before creating any module instances
    // 'true' enables VCD tracing capability
    Verilated::traceEverOn(true);
    
    // ========================================================================
    // PHASE 2: MODULE INSTANTIATION
    // ========================================================================
    // Create an instance of the top-level SystemVerilog module
    // 
    // MEMORY ALLOCATION:
    //   - 'new' allocates memory on the heap (not stack)
    //   - Returns pointer to allocated object
    //   - Object persists until explicitly deleted
    // 
    // MODULE REPRESENTATION:
    //   - Verilator compiles SystemVerilog module to C++ class
    //   - Class instance represents the entire design hierarchy
    //   - All submodules are part of this top-level instance
    // 
    // 'new' allocates memory on the heap for the module instance
    // The module was compiled by Verilator from data_structures_example.sv
    // This instance represents the entire SystemVerilog design
    Vdata_structures_example* top = new Vdata_structures_example;
    
    // ========================================================================
    // PHASE 3: WAVEFORM TRACING SETUP
    // ========================================================================
    // Create a VCD trace file object for waveform generation
    // 
    // VCD FILE OBJECT:
    //   - Manages VCD file creation and writing
    //   - Handles signal value formatting
    //   - Manages file I/O operations
    // 
    // VCD files record signal value changes over time for debugging
    VerilatedVcdC* tfp = new VerilatedVcdC;
    
    // Connect the module to the trace file object
    // 
    // TRACE REGISTRATION:
    //   - 'trace()' method registers all signals in the module for tracing
    //   - Recursively registers signals in submodules
    //   - Creates signal definitions in VCD file
    // 
    // TRACE DEPTH:
    //   - Second parameter (99) is the trace depth
    //   - Depth = how many hierarchy levels to trace
    //   - 99 = trace all levels (practical maximum)
    //   - Lower depth = smaller VCD files, faster simulation
    // 
    // 'trace()' method registers all signals in the module for tracing
    // Second parameter (99) is the trace depth (how many hierarchy levels to trace)
    // Depth 99 traces all levels of the design hierarchy
    top->trace(tfp, 99);
    
    // Open the VCD file for writing
    // 
    // FILE OPERATIONS:
    //   - Creates new file or overwrites existing file
    //   - Writes VCD header (signal definitions, timescale, etc.)
    //   - File remains open until close() is called
    // 
    // "data_structures_example.vcd" is the output filename
    // This file will contain all signal transitions during simulation
    // 
    // ERROR HANDLING (production code):
    //   if (!tfp->isOpen()) {
    //       std::cerr << "Failed to open VCD file" << std::endl;
    //       return 1;
    //   }
    tfp->open("data_structures_example.vcd");
    
    // ========================================================================
    // PHASE 4: INITIAL EVALUATION
    // ========================================================================
    // Perform initial evaluation of the design
    // 
    // EVALUATION SEMANTICS:
    //   - 'eval()' evaluates all combinational and sequential logic
    //   - Processes all always blocks, continuous assignments
    //   - Updates all signals based on current state
    //   - Required before first time step
    // 
    // 'eval()' evaluates all combinational and sequential logic
    // This initializes all signals to their reset/default values
    top->eval();
    
    // Dump initial state to VCD file at time 0
    // 
    // INITIAL STATE CAPTURE:
    //   - Records all signal values at simulation start
    //   - Essential for waveform viewer (shows initial values)
    //   - Time 0 represents "before simulation starts"
    // 
    // This captures the initial values of all traced signals
    tfp->dump(main_time);  // main_time = 0 at this point
    
    // ========================================================================
    // PHASE 5: SIMULATION LOOP
    // ========================================================================
    // Main simulation loop: run until finish or timeout
    // 
    // LOOP CONDITIONS:
    //   - 'Verilated::gotFinish()': Returns true when SystemVerilog $finish is called
    //   - 'main_time < 1000': Prevents infinite loops (timeout after 1000 time units)
    //   - Both conditions must be false to continue (logical AND)
    // 
    // SIMULATION TIME STEP:
    //   - Each iteration = one time unit (1ns based on timescale)
    //   - Time advances: 0, 1, 2, 3, ... up to 1000 or until $finish
    //   - Design is evaluated at each time step
    // 
    // 'Verilated::gotFinish()' returns true when SystemVerilog $finish is called
    // 'main_time < 1000' prevents infinite loops (timeout after 1000 time units)
    while (!Verilated::gotFinish() && main_time < 1000) {
        // Increment simulation time by one time unit
        // 
        // TIME ADVANCEMENT:
        //   - Time increases: 0 -> 1 -> 2 -> 3 -> ...
        //   - Each increment = 1 time unit (1ns from timescale)
        //   - Time is global (affects all $time calls in SystemVerilog)
        // 
        // Each iteration represents one time step in the simulation
        main_time++;
        
        // Evaluate the design at the new time step
        // 
        // EVALUATION PROCESS:
        //   1. Combinational logic: Evaluated immediately
        //   2. Sequential logic: Updates on clock edges (if any)
        //   3. Signal updates: All signals updated based on logic
        //   4. Side effects: $display, $finish, etc. executed
        // 
        // This updates all signals based on current inputs and state
        // Combinational logic is evaluated, sequential logic updates on clock edges
        top->eval();
        
        // Dump current signal values to VCD file
        // 
        // WAVEFORM RECORDING:
        //   - Records signal values at current time
        //   - Only records changes (VCD format is efficient)
        //   - Timestamped with main_time value
        // 
        // This records the state of all traced signals at this time point
        tfp->dump(main_time);
    }
    
    // ========================================================================
    // PHASE 6: CLEANUP
    // ========================================================================
    // Finalize the simulation
    // 
    // FINALIZATION:
    //   - Performs cleanup operations
    //   - Final evaluation of design
    //   - Closes any open resources in module
    //   - Ensures all final states are properly recorded
    // 
    // 'final()' performs cleanup operations and final evaluations
    // This ensures all final states are properly recorded
    top->final();
    
    // Close the VCD trace file
    // 
    // FILE CLOSURE:
    //   - Flushes any remaining data to disk
    //   - Finalizes VCD file format
    //   - Closes file handle
    //   - File is now ready for waveform viewers
    // 
    // This flushes any remaining data and finalizes the file format
    // The file can now be opened in waveform viewers
    tfp->close();
    
    // Deallocate the top-level module instance
    // 
    // MEMORY DEALLOCATION:
    //   - 'delete' frees the memory allocated by 'new'
    //   - Calls destructor (cleanup in module)
    //   - Prevents memory leaks
    //   - Best practice: Delete in reverse order of allocation
    // 
    // 'delete' frees the memory allocated by 'new'
    // This prevents memory leaks
    delete top;
    
    // Deallocate the VCD trace file object
    // 
    // Clean up the trace file handler
    delete tfp;
    
    // Return success status to the operating system
    // 
    // EXIT CODES:
    //   - 0: Success (normal termination)
    //   - Non-zero: Error (should be used for error conditions)
    // 
    // Exit code 0 indicates successful completion
    return 0;
}
